/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package purchase_with_login_frame.Panels;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import purchase_with_login_frame.DetailsFrame;
import purchase_with_login_frame.LoginFrame;
import static purchase_with_login_frame.LoginFrame.username;
import static purchase_with_login_frame.WelcomePage.Cust_ID;

/**
 *
 * @author Admin
 */
public class Micro_Controller_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Micro_Controller_Panel
     */
    public Micro_Controller_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1265, 377));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/aurdino_uno.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/download-2.jpg"))); // NOI18N
        jLabel2.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/upload-d41c4b22-96ea-4fa2-bb8e-bbcc07996aa4.jpeg"))); // NOI18N

        jLabel4.setText("Arduino Uno micro-controller");

        jLabel5.setText("Raspberry Pi V3 micro-controller");

        jLabel6.setText("Lynx motion ssc32 board");

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Quantity:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Quantity:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Quantity:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButton1)
                .addGap(358, 358, 358)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel4)
                .addGap(236, 236, 236)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 8");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 8" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField3.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 9");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 9" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField4.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 10");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 10" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField5.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    public static String setText(String username) 
    {      
        System.out.println(username);
        return username;
    }

    int setInt(int Cust_ID) 
    {
        System.out.println(Cust_ID);
        return Cust_ID;
    } 
}
