/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package purchase_with_login_frame.Panels;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import purchase_with_login_frame.DetailsFrame;
import purchase_with_login_frame.LoginFrame;
import static purchase_with_login_frame.LoginFrame.username;
import static purchase_with_login_frame.WelcomePage.Cust_ID;

/**
 *
 * @author Admin
 */
public class Washing_Machine_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Washing_Machine_Panel
     */
    public Washing_Machine_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1265, 377));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/item_L_4909012_1550315.jpg"))); // NOI18N

        jLabel2.setText("Samsung 8Kg Twin Tub Washing Machine (Model: WT13J7)");

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/GTW460ASJWW_280x@2x.jpg"))); // NOI18N

        jLabel4.setText("GE GTW460ASJWW 27 Inch 4.2 cu. ft. Top Load Washer");

        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchase_with_login_frame/Panels/mgd7000ag_3_588625b7629a6.jpg"))); // NOI18N

        jLabel6.setText("Maytag MGD7000AG 27\" Titanium Gas Dryer 7.4 Cu. Ft.");

        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Quantity:");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel14.setText("Quantity:");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel15.setText("Quantity:");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1)
                .addGap(367, 367, 367)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 17");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 17" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField7.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 19");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 19" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField9.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        String Itxt1,Itxt2,Itxt3;
        String txt1,txt2,txt3;
        String user = setText(username);
        int customerid = setInt(Cust_ID);
        int prod;
        
        int max = 10000;
        int min = 1; 
        Random randomnum = new Random();
        int showMe = min + randomnum.nextInt(max);
        System.out.println(showMe);
        
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            System.out.println("Going to connect to database");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/E-Commerce Application;create=true");
            System.out.println("Connection Successfull");
            PreparedStatement stmt = conn.prepareStatement("SELECT PRODUCT_ID FROM APP.PRODUCTDETAILS WHERE PRODUCT_ID = 18");
            PreparedStatement stmt1 = conn1.prepareStatement("UPDATE APP.CUSTOMERDETAILS SET PRODUCT_ID = ? WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt2 = conn.prepareStatement("SELECT CUSTOMER_ID FROM APP.CUSTOMERDETAILS WHERE CUSTOMER_ID =" + customerid);
            PreparedStatement stmt3 = conn1.prepareStatement("UPDATE APP.PRODUCTDETAILS SET CUSTOMER_ID = ? WHERE PRODUCT_ID = 18" );
            ResultSet rs=stmt2.executeQuery();
            ResultSet rst=stmt.executeQuery();
            
            while(rst.next() && rs.next())
            {
                System.out.println("Entering the loop");
                stmt1.setString(1, rst.getString("PRODUCT_ID"));
                stmt3.setInt(1,customerid);
                System.out.println(customerid);
                
                stmt1.executeUpdate();
                stmt3.executeUpdate();
            }
            try
                {
                    PreparedStatement pstmt = conn.prepareStatement("SELECT pd.PRODUCT_ID, pd.PRODUCTNAME, pd.QUANTITY, pd.PRICE, cd.CUSTOMER_ID  FROM APP.PRODUCTDETAILS pd, APP.CUSTOMERDETAILS cd WHERE cd.PRODUCT_ID = pd.PRODUCT_ID AND cd.CUSTOMER_ID =" + customerid);
                    PreparedStatement pstmt1 = conn1.prepareStatement("INSERT INTO APP.ORDERDETAILS (ORDER_NUMBER, PRODUCT_ID, PRODUCTNAME, QUANTITY, PRICE, CUSTOMER_ID) VALUES (?, ?, ?, ?, ?, ?)");
                    ResultSet rst1= pstmt.executeQuery();
                    while(rst1.next())
                    {
                        /*
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, rst1.getString("QUANTITY"));
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                */
                        pstmt1.setInt(1, showMe);
                        pstmt1.setString(2, rst1.getString("PRODUCT_ID"));
                        pstmt1.setString(3, rst1.getString("PRODUCTNAME"));
                        pstmt1.setString(4, jTextField8.getText());
                        pstmt1.setString(5, rst1.getString("PRICE"));
                        System.out.println("customerid" + customerid );
                        pstmt1.setInt(6, rst1.getInt("CUSTOMER_ID"));
                        pstmt1.executeUpdate();
                    }
                }catch(Exception ex)
                {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                }
        } catch(Exception ex)
                    {
                    System.err.println("Got an exception!"); 
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Got an exception: "+ex.getMessage());
                    }
            finally{
                try {
                    conn.close();
                    conn1.close();
                } catch (SQLException ex) 
                {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }    
            } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    public static String setText(String username) 
    {      
        System.out.println(username);
        return username;
    }

    int setInt(int Cust_ID) 
    {
        System.out.println(Cust_ID);
        return Cust_ID;
    } 
}
